export default {
  themeMode: 'light',
  backgroundColor: '#FFF',
  bubbleBorderColor: '#E2DACC',
  bubbleMyMessage: '',
  menuIcon: '#9945FF',
  tabNavHeader: 'white',
  textColor: '#1c1e21',
  textColorPrimary: '#32d48e',
  textColorHeading: '#32d48e',
  'colors--------': '',
  blue: '#3498db',
  lightGrey: '#bdc3c7',
  extraLightGrey: '#ededed',
  nearlyWhite: '#F4F8F7',
  grey: '#7f8c8d',
  primary: '#32d48e',
  red: '#e74c3c',
  beige: '#FEF5C3',
  solanaGreen: '#14F195',
  solanaPurple: '#9945FF',
}
