export default {
  themeMode: 'light',
  backgroundImageUri: '../../../assets/images/solana/Solana_Glass_03.png',
  backgroundColor: '#FFF',
  blue: '#3498db',
  lightGrey: '#bdc3c7',
  extraLightGrey: '#ededed',
  nearlyWhite: '#F4F8F7',
  grey: '#7f8c8d',
  textColor: '#1c1e21',
  primary: '#32d48e',
  red: '#e74c3c',
  beige: '#FEF5C3',
  solanaGreen: '#14F195',
  solanaPurple: '#9945FF',
  menuIcon: '#9945FF',
}
